// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// exponential_ma
NumericVector exponential_ma(const NumericVector& x, double alpha, int n_init);
RcppExport SEXP _ssmooth_exponential_ma(SEXP xSEXP, SEXP alphaSEXP, SEXP n_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n_init(n_initSEXP);
    rcpp_result_gen = Rcpp::wrap(exponential_ma(x, alpha, n_init));
    return rcpp_result_gen;
END_RCPP
}
// simple_ma
NumericVector simple_ma(const NumericVector& x, int n);
RcppExport SEXP _ssmooth_simple_ma(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(simple_ma(x, n));
    return rcpp_result_gen;
END_RCPP
}
// weighted_ma
NumericVector weighted_ma(const NumericVector& x, const NumericVector& w);
RcppExport SEXP _ssmooth_weighted_ma(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_ma(x, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ssmooth_exponential_ma", (DL_FUNC) &_ssmooth_exponential_ma, 3},
    {"_ssmooth_simple_ma", (DL_FUNC) &_ssmooth_simple_ma, 2},
    {"_ssmooth_weighted_ma", (DL_FUNC) &_ssmooth_weighted_ma, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ssmooth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
