# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exponential_ma <- function(x, alpha, n_init) {
    .Call(`_ssmooth_exponential_ma`, x, alpha, n_init)
}

simple_ma <- function(x, n) {
    .Call(`_ssmooth_simple_ma`, x, n)
}

weighted_ma <- function(x, w) {
    .Call(`_ssmooth_weighted_ma`, x, w)
}

